name: Notify Telegram on Push

on:
  push:
    branches: # This will trigger the workflow on any branch push
      - '**' # Matches all branches
  pull_request:
    branches: # This will trigger the workflow on pull request events for all branches
      - '**' # Matches all branches
  issue_comment: # This will notify on issue comments (optional)
  issues: # This will notify on issues opened/closed (optional)
  create: # This will notify when a branch or tag is created (optional)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "🚀 New push to main branch!\nRepo: ${{ github.repository }}\nCommit: ${{ github.event.head_commit.message }}"}'
