name: Notify Telegram on GitHub Events
#hello
on:
  push:
    branches:
      - '**' # Trigger on push to any branch
  pull_request:
    branches:
      - '**' # Trigger on pull request for any branch
  issue_comment:
    types: [created] # Trigger on issue comment creation (optional)
  issues:
    types: [opened, closed] # Trigger on issue opened or closed (optional)
  create: # Trigger on new branch creation (optional)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          # Check if it's a push event and get the commit message
          COMMIT_MESSAGE="${{ github.event.head_commit.message || 'No commit message available' }}"

          # Format the message with Markdown
          MESSAGE="*🚨 Event Triggered:*\n\n*Event:* \`${{ github.event_name }}\`\n*Repository:* \`${{ github.repository }}\`\n*Branch:* \`${{ github.ref }}\`\n*Commit:* \`${COMMIT_MESSAGE}\`\n*Commit Author:* \`${{ github.event.head_commit.author.name }}\`\n\n*Triggered by:* \`${{ github.actor }}\`\n*Action:* \`${{ github.event_name }}\`"

          # Send the notification
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "'"$MESSAGE"'", "parse_mode": "Markdown"}'
